#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#
#   *** Serial Job on Normal Queue ***
# 
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Copy/edit this script as desired.  Launch by executing
#      "sbatch knl.serial.slurm" on a Stampede2 login node.
#
#   -- Serial codes run on a single node (upper case N = 1).
#        A serial code ignores the value of lower case n,
#        but slurm needs a plausible value to schedule the job.
#
#   -- For a good way to run multiple serial executables at the
#        same time, execute "module load launcher" followed
#        by "module help launcher".

#----------------------------------------------------

#SBATCH -J sp1          # Job name
#SBATCH -o sp1.o%j       # Name of stdout output file
#SBATCH -e sp1.e%j       # Name of stderr error file
#SBATCH -p normal          # Queue (partition) name
#SBATCH -N 3               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 02:00:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=skmadan@utexas.edu

# Other commands must follow all #SBATCH directives...

module load gcc
module load boost

# Launch serial code...

$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo dijkstra -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo dijkstraTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo serDelta -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo serDeltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo deltaStep -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo deltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo topo -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo topoTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/rome99.gr -algo serSP1 -delta 13 -t 40

$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo dijkstra -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo dijkstraTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo serDelta -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo serDeltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo deltaStep -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo deltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo topo -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo topoTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/structured/torus5.gr -algo serSP1 -delta 13 -t 40


$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo dijkstra -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo dijkstraTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo serDelta -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo serDeltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo deltaStep -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo deltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo topo -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo topoTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/scalefree/rmat8-2e14.gr -algo serSP1 -delta 13 -t 40


$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo dijkstra -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo dijkstraTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo serDelta -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo serDeltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo deltaStep -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo deltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo topo -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo topoTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/road/USA-road-d.USA.gr -algo serSP1 -delta 13 -t 40


$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo dijkstra -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo dijkstraTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo serDelta -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo serDeltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo deltaStep -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo deltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo topo -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo topoTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e23.gr -algo serSP1 -delta 13 -t 40


$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo dijkstra -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo dijkstraTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo serDelta -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo serDeltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo deltaStep -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo deltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo topo -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo topoTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e24.gr -algo serSP1 -delta 13 -t 40


$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo dijkstra -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo dijkstraTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo serDelta -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo serDeltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo deltaStep -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo deltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo topo -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo topoTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/random/r4-2e26.gr -algo serSP1 -delta 13 -t 40


$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo dijkstra -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo dijkstraTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo serDelta -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo serDeltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo deltaStep -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo deltaTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo topo -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo topoTile -delta 13 -t 40
$SCRATCH/galois-garg/build/lonestar/sssp/sssp $SCRATCH/galois-garg/build/inputs/reference/r.100M.250M.gr -algo serSP1 -delta 13 -t 40

#----------------------------------------------------
