#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#
#   *** Serial Job on Normal Queue ***
# 
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Copy/edit this script as desired.  Launch by executing
    #  "sbatch knl.serial.slurm" on a Stampede2 login node.
#
#   -- Serial codes run on a single node (upper case N = 1).
    #    A serial code ignores the value of lower case n,
    #    but slurm needs a plausible value to schedule the job.
#
#   -- For a good way to run multiple serial executables at the
    #    same time, execute "module load launcher" followed
    #    by "module help launcher".

#----------------------------------------------------

#SBATCH -J sp1          # Job name
#SBATCH -o sp1.o%j       # Name of stdout output file
#SBATCH -e sp1.e%j       # Name of stderr error file
#SBATCH -p skx-normal          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 02:00:00        # Run time (hh:mm:ss)

# Other commands must follow all #SBATCH directives...

module load boost
module load intel/18.0.2

# Launch serial code...

program='sssp'
testcase='galois'
path='/work/05888/madansk/stampede2/repository/galois-garg/build/lonestar/sssp/'
algos='serSP2'
threads=20

for i in "$@"
do
case $i in
    -h|--help)
    printf "Usage: \n"
    printf "	-p, --path: relative path to directory containing sssp executable\n"
    printf "	-pr, --program: Program to run (sssp, apsp)\n"
    printf "	-ts, --test_suite: Test Suite to use (galois, small, moderate, large)\n"
    printf "	-a, --algo: Algorithm (dijkstra, dijkstraTile, serSP1, parSP1, serSP2, parSP2V, parSP2E, serDelta, serDeltaTile, deltaStep, deltaTile, topo, topoTile)\n"
    printf "	-th, --threads: Number of Threads to use (WARNING: depends on the machine's processor)\n\n"
    exit
    ;;
    -p=*|--path=*)
    path="${i#*=}"
    shift
    ;;
    -ts=*|--test_suite=*)
    testcase="${i#*=}"
    shift
    ;;
    -pr=*|--program=*)
    program="${i#*=}"
    shift
    ;;
    -a=*|--algo=*)
    algos="${i#*=}"
    shift
    ;;
    -th=*|--threads=*)
    threads="${i#*=}"
    shift
    ;;
    --default)
    DEFAULT=YES
    shift
    ;;
    *)
    ;;
esac
done

if [ ${program} = 'sssp' ]
then
  if [ ${testcase} = 'galois' ]
  then
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/rmat8-2e14.gr -algo ${algos} -t ${threads}   									 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/structured/rome99.gr -algo ${algos} -t ${threads}   										
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/road/USA-road-d.USA.gr -algo ${algos} -t ${threads}   										
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/random/r4-2e23.gr -algo ${algos} -t ${threads}   											
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/structured/torus5.gr -algo ${algos} -t ${threads}   										
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/random/r4-2e24.gr -algo ${algos} -t ${threads}   											
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/random/r4-2e26.gr -algo ${algos} -t ${threads}   											
  fi

  if [ ${testcase} = 'small' ]
  then
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG2_rand.gr -algo ${algos} -t ${threads} 								      #164K 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG2.gr -algo ${algos} -t ${threads}                                                                      #164K 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG3_rand.gr -algo ${algos} -t ${threads}                                                                     #168K 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG3.gr -algo ${algos} -t ${threads}                                                                      #168K 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG1_rand.gr -algo ${algos} -t ${threads}                                                                      #408K 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG1.gr -algo ${algos} -t ${threads}                                                                       #408K 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/coAuthorsCiteseer_rand.gr -algo ${algos} -t ${threads}                                           #8.0M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/coAuthorsCiteseer.gr -algo ${algos} -t ${threads}                                            #8.0M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/coAuthorsDBLP_rand.gr -algo ${algos} -t ${threads}                                              #9.8M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/coAuthorsDBLP.gr -algo ${algos} -t ${threads}                                               #9.8M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/citationCiteseer_rand.gr -algo ${algos} -t ${threads}                                           # 11M  
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/citationCiteseer.gr -algo ${algos} -t ${threads}                                            # 11M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/random/Knowledge_Repo_rand.gr -algo ${algos} -t ${threads}                                                       # 12M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/unweighted/Knowledge_Repo.gr -algo ${algos} -t ${threads}                                                        # 12M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/kron/kron_g500-logn16.gr -algo ${algos} -t ${threads}                                                           # 20M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/kron/kron_g500-simple-logn16.gr -algo ${algos} -t ${threads}                                                    # 20M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/random/Belgium_rand.gr -algo ${algos} -t ${threads}                                                           # 23M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/unweighted/Belgium.gr -algo ${algos} -t ${threads}                                                            # 23M  
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/random/CA_RoadNet_rand.gr -algo ${algos} -t ${threads}                                                          # 58M  
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/unweighted/CA_RoadNet.gr -algo ${algos} -t ${threads}                                                           # 58M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-s18-ef16_rand.gr -algo ${algos} -t ${threads}                                           # 60M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-s18-ef16.gr -algo ${algos} -t ${threads}                                                    # 60M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/random/er-fact1.5-scale20_rand.gr -algo ${algos} -t ${threads}                                                # 92M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/unweighted/er-fact1.5-scale20.gr -algo ${algos} -t ${threads}                                                 # 92M  
  fi                                                                                                                                


  if [ ${testcase} = 'moderate' ]
  then                                                                                                                             
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/random/Italy_rand.gr -algo ${algos} -t ${threads}                                                             #105M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/unweighted/Italy.gr -algo ${algos} -t ${threads}                                                              #105M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/random/Watson_Gene_rand.gr -algo ${algos} -t ${threads}                                                          #109M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/unweighted/Watson_Gene.gr -algo ${algos} -t ${threads}                                                           #109M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/coPapersDBLP_rand.gr -algo ${algos} -t ${threads}                                                #121M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/coPapersDBLP.gr -algo ${algos} -t ${threads}                                                 #121M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-s19-ef16_rand.gr -algo ${algos} -t ${threads}                                           #121M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-s19-ef16.gr -algo ${algos} -t ${threads}                                                    #121M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/random/Britain_rand.gr -algo ${algos} -t ${threads}                                                          #122M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/unweighted/Britain.gr -algo ${algos} -t ${threads}                                                           #122M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/coPapersCiteseer_rand.gr -algo ${algos} -t ${threads}                                           #126M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/coPapersCiteseer.gr -algo ${algos} -t ${threads}                                            #126M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/kron/kron_g500-logn19.gr -algo ${algos} -t ${threads}                                                           #171M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/kron/kron_g500-simple-logn19.gr -algo ${algos} -t ${threads}                                                    #171M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/random/Asia_rand.gr -algo ${algos} -t ${threads}                                                             #189M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/unweighted/Asia.gr -algo ${algos} -t ${threads}                                                              #189M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/random/er-fact1.5-scale21_rand.gr -algo ${algos} -t ${threads}                                                #191M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/unweighted/er-fact1.5-scale21.gr -algo ${algos} -t ${threads}                                                 #191M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-s20-ef16_rand.gr -algo ${algos} -t ${threads}                                          #245M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-s20-ef16.gr -algo ${algos} -t ${threads}                                                   #245M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/random/er-fact1.5-scale22_rand.gr -algo ${algos} -t ${threads}                                               #399M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/unweighted/er-fact1.5-scale22.gr -algo ${algos} -t ${threads}                                                #399M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-s21-ef16_rand.gr -algo ${algos} -t ${threads}                                          #494M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-s21-ef16.gr -algo ${algos} -t ${threads}                                                   #494M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/random/er-fact1.5-scale23_rand.gr -algo ${algos} -t ${threads}                                               #830M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/unweighted/er-fact1.5-scale23.gr -algo ${algos} -t ${threads}                                                #830M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-s22-ef16_rand.gr -algo ${algos} -t ${threads}                                          #997M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-s22-ef16.gr -algo ${algos} -t ${threads}                                                   #997M 
  fi

  if [ ${testcase} = 'large' ]                                                                                                                             
  then                                                                                                                             
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/random/er-fact1.5-scale24_rand.gr -algo ${algos} -t ${threads}                                                #1.7G 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/unweighted/er-fact1.5-scale24.gr -algo ${algos} -t ${threads}                                                 #1.7G 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG1_ParMAT_rand.gr -algo ${algos} -t ${threads}                                                               #1.9G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG2_ParMAT_rand.gr -algo ${algos} -t ${threads}                                                              #1.9G 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG1_ParMAT.gr -algo ${algos} -t ${threads}                                                                #1.9G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG2_ParMAT.gr -algo ${algos} -t ${threads}                                                               #1.9G 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/PARMAT/random/ParMAT_100M_160M_rand.gr -algo ${algos} -t ${threads}                                                       #2.0G 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/PARMAT/unweighted/ParMAT_100M_160M.gr -algo ${algos} -t ${threads}                                                        #2.0G 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-s23-ef16_rand.gr -algo ${algos} -t ${threads}                                           #2.0G 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-s23-ef16.gr -algo ${algos} -t ${threads}                                                    #2.0G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG3_ParMAT_rand.gr -algo ${algos} -t ${threads}                                                              #2.3G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG3_ParMAT.gr -algo ${algos} -t ${threads}                                                               #2.3G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/PARMAT/random/ParMAT_150M_160M_rand.gr -algo ${algos} -t ${threads}                                                      #2.8G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/PARMAT/unweighted/ParMAT_150M_160M.gr -algo ${algos} -t ${threads}                                                       #2.8G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-scale24-ef16_adj_rand.gr -algo ${algos} -t ${threads}                                  #4.0G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-scale24-ef16_adj.gr -algo ${algos} -t ${threads}                                           #4.0G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-scale25-ef16_adj_rand.gr -algo ${algos} -t ${threads}                                  #8.0G 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-scale25-ef16_adj.gr -algo ${algos} -t ${threads}                                           #8.0G 
  fi

  if [ ${testcase} = 'kron-small' ]
  then
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e14.gr -algo ${algos} -t ${threads}                                                                       #372K   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e15.gr -algo ${algos} -t ${threads}                                                                       #792K   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e16.gr -algo ${algos} -t ${threads}                                                                       #1.7M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e17.gr -algo ${algos} -t ${threads}                                                                       #3.6M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e18.gr -algo ${algos} -t ${threads}                                                                       #7.6M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e19.gr -algo ${algos} -t ${threads}                                                                       #17M    
  fi

  if [ ${testcase} = 'kron-moderate' ]
  then
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e20.gr -algo ${algos} -t ${threads}                                                                       #35M    
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e21.gr -algo ${algos} -t ${threads}                                                                       #76M    
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e22.gr -algo ${algos} -t ${threads}                                                                       #163M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e23.gr -algo ${algos} -t ${threads}                                                                       #351M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e24.gr -algo ${algos} -t ${threads}                                                                       #759M   
  fi

  if [ ${testcase} = 'kron-large' ]
  then
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e25.gr -algo ${algos} -t ${threads}                                                                       #1.7G   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e26.gr -algo ${algos} -t ${threads}                                                                       #3.5G   
  fi
fi

if [ ${program} = 'apsp' ]
then
  if [ ${testcase} = 'galois' ]
  then
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/rmat8-2e14.gr -algo ${algos} -t ${threads} -apsp
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/structured/rome99.gr -algo ${algos} -t ${threads}  -apsp  								
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road/USA-road-d.USA.gr -algo ${algos} -t ${threads}  -apsp  								
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/random/r4-2e23.gr -algo ${algos} -t ${threads}   -apsp 										
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/structured/torus5.gr -algo ${algos} -t ${threads}  -apsp  									 
  fi

  if [ ${testcase} = 'small' ]
  then
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG2_rand.gr -algo ${algos} -t ${threads}  -apsp						              #164K 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG2.gr -algo ${algos} -t ${threads}   -apsp                                                              #164K 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG3_rand.gr -algo ${algos} -t ${threads}  -apsp                                                              #168K 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG3.gr -algo ${algos} -t ${threads}   -apsp                                                              #168K 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/random/DAG1_rand.gr -algo ${algos} -t ${threads}  -apsp                                                               #408K 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/DAG/unweighted/DAG1.gr -algo ${algos} -t ${threads}   -apsp                                                               #408K 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/coAuthorsCiteseer_rand.gr -algo ${algos} -t ${threads} -apsp                                     #8.0M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/coAuthorsCiteseer.gr -algo ${algos} -t ${threads}  -apsp                                     #8.0M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/coAuthorsDBLP_rand.gr -algo ${algos} -t ${threads}     -apsp                                    #9.8M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/coAuthorsDBLP.gr -algo ${algos} -t ${threads}-apsp                                          #9.8M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/citationCiteseer_rand.gr -algo ${algos} -t ${threads}  -apsp                                    # 11M  
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/citationCiteseer.gr -algo ${algos} -t ${threads}   -apsp                                    # 11M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/random/Knowledge_Repo_rand.gr -algo ${algos} -t ${threads}-apsp                                                  # 12M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/unweighted/Knowledge_Repo.gr -algo ${algos} -t ${threads} -apsp                                                  # 12M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/kron/kron_g500-logn16.gr -algo ${algos} -t ${threads}  -apsp                                                    # 20M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/kron/kron_g500-simple-logn16.gr -algo ${algos} -t ${threads}   -apsp                                            # 20M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/random/Belgium_rand.gr -algo ${algos} -t ${threads}  -apsp                                                    # 23M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/unweighted/Belgium.gr -algo ${algos} -t ${threads}   -apsp                                                    # 23M  
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/random/CA_RoadNet_rand.gr -algo ${algos} -t ${threads}  -apsp                                                   # 58M  
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/unweighted/CA_RoadNet.gr -algo ${algos} -t ${threads}   -apsp                                                   # 58M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-s18-ef16_rand.gr -algo ${algos} -t ${threads} -apsp                                     # 60M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-s18-ef16.gr -algo ${algos} -t ${threads} -apsp                                              # 60M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/random/er-fact1.5-scale20_rand.gr -algo ${algos} -t ${threads} -apsp                                          # 92M  
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/unweighted/er-fact1.5-scale20.gr -algo ${algos} -t ${threads} -apsp                                           # 92M  
  fi                                                                                                                                

  if [ ${testcase} = 'moderate' ]
  then                                                                                                                             
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/random/Italy_rand.gr -algo ${algos} -t ${threads}  -apsp                                                     #105M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/unweighted/Italy.gr -algo ${algos} -t ${threads}   -apsp                                                     #105M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/random/Watson_Gene_rand.gr -algo ${algos} -t ${threads} -apsp                                                    #109M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/graphBIG/unweighted/Watson_Gene.gr -algo ${algos} -t ${threads} -apsp                                                     #109M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/coPapersDBLP_rand.gr -algo ${algos} -t ${threads} -apsp                                          #121M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/coPapersDBLP.gr -algo ${algos} -t ${threads} -apsp                                           #121M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/random_weights/graph500-s19-ef16_rand.gr -algo ${algos} -t ${threads} -apsp                                     #121M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/unweighted/graph500-s19-ef16.gr -algo ${algos} -t ${threads} -apsp                                              #121M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/random/Britain_rand.gr -algo ${algos} -t ${threads} -apsp                                                    #122M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/unweighted/Britain.gr -algo ${algos} -t ${threads} -apsp                                                     #122M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/random/coPapersCiteseer_rand.gr -algo ${algos} -t ${threads} -apsp                                     #126M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/citation_networks/unweighted/coPapersCiteseer.gr -algo ${algos} -t ${threads} -apsp                                      #126M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/kron/kron_g500-logn19.gr -algo ${algos} -t ${threads} -apsp                                                     #171M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/power_law/kron/kron_g500-simple-logn19.gr -algo ${algos} -t ${threads} -apsp                                              #171M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/random/Asia_rand.gr -algo ${algos} -t ${threads} -apsp                                                       #189M 
    #${path}/sssp /work/05888/madansk/stampede2/input_graphs/road_graphs/unweighted/Asia.gr -algo ${algos} -t ${threads} -apsp                                                        #189M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/random/er-fact1.5-scale21_rand.gr -algo ${algos} -t ${threads} -apsp                                          #191M 
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/erdos_renyi/unweighted/er-fact1.5-scale21.gr -algo ${algos} -t ${threads} -apsp                                           #191M 
  fi

  if [ ${testcase} = 'kron-small' ]
  then
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e14.gr -algo ${algos} -t ${threads} -apsp                                                                 #372K   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e15.gr -algo ${algos} -t ${threads} -apsp                                                                 #792K   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e16.gr -algo ${algos} -t ${threads} -apsp                                                                 #1.7M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e17.gr -algo ${algos} -t ${threads} -apsp                                                                 #3.6M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e18.gr -algo ${algos} -t ${threads} -apsp                                                                 #7.6M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e19.gr -algo ${algos} -t ${threads} -apsp                                                                 #17M    
  fi

  if [ ${testcase} = 'kron-moderate' ]
  then
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e20.gr -algo ${algos} -t ${threads} -apsp                                                                 #35M    
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e21.gr -algo ${algos} -t ${threads} -apsp                                                                 #76M    
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e22.gr -algo ${algos} -t ${threads} -apsp                                                                 #163M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e23.gr -algo ${algos} -t ${threads} -apsp                                                                 #351M   
    ${path}/sssp /work/05888/madansk/stampede2/input_graphs/scalefree/kron-2e24.gr -algo ${algos} -t ${threads} -apsp                                                                 #759M   
  fi
fi
#----------------------------------------------------
